---
title: "BM1 project"
author: "Chen Li"
date: "December 10, 2017"
output: html_document
---

```{r setup, echo = FALSE, message = FALSE, results = FALSE, warning = FALSE}


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%")
library(readxl)
library(tidyverse)
library(janitor)
library(faraway)
library(broom)
library(dplyr)
library(haven)
library(rvest)
library(stringr)
library(forcats)
#create fxn for full library load
#watch jg lecture videos for this hw


```


```{r clean dataset}
patientdata = read_excel("GHProject_Dataset.xlsx") %>% 
  clean_names()%>%
  separate(admitdtm, into = c("week", "month","year"), sep = ",")%>%
  mutate(
         day = str_sub(month,-3,-1),
       month = str_sub(month, 1, -4))%>%
  mutate(month= as.numeric(factor(substr(month,2,4), levels = month.abb)))%>%
  arrange(by=patientid,year,month, day)%>%
  distinct(patientid, .keep_all = TRUE) %>% 
  rename(
    age = ageyear, 
    marital_status = maritalstatus, 
    insurance_type = insurancetype,
    facility = facilityname, 
    facility_zip = facilityzip,
    postal_code = postalcode,
    los_hours = loshours, 
    los_days = losdays2,
    o2_sat = o2sat,
    respiration_rate = respirationrate, 
    heart_rate = heartrate, 
    bp_systolic = bpsystolic, 
    bp_diastolic = bpdiastolic, 
    patient_id = patientid, 
    visit_id = visitid) %>% 
  mutate(
    los_days = round(los_days, 2),
    temperature = round(temperature, 2),
    bmi = round(bmi, 2),
    respiration_rate = round(respiration_rate, 2),
    o2_sat = round(o2_sat, 2),
    heart_rate = round(heart_rate, 2), 
    bp_systolic = round(bp_systolic, 2), 
    bp_diastolic = round(bp_diastolic, 2))

patientdata %>% 
  count(race)
```
  
  
```{r factor recoding}
# cindex: 0=normal,1-2=mild,3-4=moderate,>5=severe
patientdata= patientdata %>%
mutate( cindex = factor(cindex),
        cindex = fct_recode(cindex, 
                         "normal" = "0",
                         "mild" = "1",
                         "mild" = "2",
                         "moderate"= "3",
                         "moderate"= "4",
                         "severe"="5"))

# gender: 0="Female",1="Male"
patientdata$gender<-ifelse(patientdata$gender == "Male",1,0)


#insurance type: 0="Medicaid", 2 = "Medicare", 3="Private"
patientdata= patientdata %>%
mutate(insurance_type = factor(insurance_type),
       insurance_type = fct_recode(insurance_type, 
                         "0" = "Medicaid",
                         "1"="Medicare",       
                         "2"="Private"))

# marital status: 0="married or living as married", 1="widowed or seperated", 2="unmarried"
patientdata= patientdata %>%
mutate( marital_status = factor(marital_status),
        marital_status = fct_recode(marital_status, 
                         "0" = "Married",
                         "0"= "Civil Union",
                         "1"= "Widowed",
                         "1" = "Separated",
                         "2"= "Single" ,
                         "2"= "Divorced"))

# mews: 0-1=normal(0), 2-3=increase caution(1), 4-5=further deterioration(2), >5 immediate action required(3)
patientdata=patientdata %>% 
mutate(mews=ifelse(mews >5,3,ifelse(mews >=4,2, ifelse(mews >=2, 1,0))))

# race
patientdata = patientdata %>%
  mutate(race = fct_recode(race, 
                         "0" = "White",
                         "1" = "African Amer/Black",       
                         "2" = "Asian",
                         "3" = "Other/Multiracial",
                         "4" = "Native Amer/Alaskan",
                         "5" = "Natv Hawaii/Pacf Isl"))


```



```{r}
patientdata = patientdata %>% 
  mutate(log_los = log(los_hours))
hist(patientdata$log_los)
```

```{r}
# interested variables
data_fit = patientdata %>%
dplyr::select(log_los,mews,is30dayreadmit,cindex,evisit,age,race,icu_flag,gender,marital_status,insurance_type,bmi,bp_systolic,o2_sat, temperature,heart_rate,respiration_rate)
```

```{r}
#stepwise : backward
mult.fit <- lm(log_los ~ ., data=data_fit)
summary(mult.fit)
step1<-update(mult.fit, . ~ . -icu_flag,data=data_fit)
tidy(step1)
step2<-update(step1, . ~ . - mews,data=data_fit)
tidy(step2)
step3<-update(step2, . ~ . - bmi,data=data_fit)
tidy(step3)
step4<-update(step3, . ~ . - race,data=data_fit)
tidy(step4)
step5<-update(step4, . ~ . - o2_sat,data=data_fit)
summary(step5)
step6<-update(step5, . ~ . - temperature,data=data_fit)
tidy(step6)
summary(step6)
#we choose lm(formula = log_los ~ is30dayreadmit + cindex + evisit + age + gender + marital_status + insurance_type + bp_systolic + heart_rate + respiration_rate, data = data_fit) as our original models, since all p-values are significant in the model.
```

```{r}
model = lm(log_los ~ is30dayreadmit + cindex + evisit + age + gender + marital_status + insurance_type + bp_systolic + heart_rate + respiration_rate, data=data_fit)
summary(model)
anova(model)
#From Anova table, we notice that p-value of gender variables are not significant.

model1 = lm(log_los ~ is30dayreadmit + cindex + evisit + age  + marital_status + insurance_type + bp_systolic + heart_rate + respiration_rate, data=data_fit)
#test correlation between age and insurance_type.
test_linear = lm(age~insurance_type, data = data_fit)
summary(test_linear)

model_age = lm(log_los ~ is30dayreadmit + cindex + evisit+ marital_status + insurance_type + bp_systolic + heart_rate + respiration_rate, data=data_fit)
summary(model_age)

model_insurance = lm(log_los ~ is30dayreadmit + cindex + evisit + age  + marital_status + bp_systolic + heart_rate + respiration_rate, data=data_fit)
summary(model_insurance)

AIC(model_age)
AIC(model_insurance)
AIC(model1)
#To compare three models r-square, it's better to drop age variable and choose model--model_insurance. This is just an assumption, we need to test this result in the following steps.


```


```{r}
data_base = data_fit%>%
 dplyr::select(is30dayreadmit,cindex,evisit,age,marital_status,insurance_type,bp_systolic,heart_rate,respiration_rate,log_los)


library(dplyr)
library(HH)
library("leaps")

# Summary of models for each size (one model per size)
b<-regsubsets(log_los ~ ., data=data_base,nvmax = 10)
   (rs<-summary(b))

# Plots of Cp and Adj-R2 as functions of parameters

par(mar=c(4,4,1,1))
par(mfrow=c(1,2))

plot(1:10, rs$cp, xlab="No of parameters", ylab="Cp Statistic")
abline(0,1)
#we should choose model with 9 or 10 parameters.
#adjusted r2: hign as much as possible: go back to cp plot, then we get six models parameters 

plot(1:10, rs$adjr2, xlab="No of parameters", ylab="Adj R2")

#hign as much as possible: go back to cp plot, then we get 9 or 10 models parameters 

best <- function(model, ...) 
{
  subsets <- regsubsets(formula(model), model.frame(model),nvmax = 10,...)
  subsets <- with(summary(subsets),
                  cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))##rss(in r) = SSE

  
  return(subsets)
}  

# Select the 'best' 2 models of all subsets
best(model, nbest = 2)

#bic: smallest values 8 predictors

# Select the 'best' 1 model of all subsets
round(best(model, nbest = 1), 8)

#lowest bic: 8 predicotrs
#Through testing, we should only choose 8 predictors(9 parameters) and drop martial_status and gender variables in the model1 and the new model 2 is:
model2 = lm(log_los ~ is30dayreadmit + cindex + evisit + age  + insurance_type + bp_systolic + heart_rate + respiration_rate, data=data_base)
summary(model2)
anova(model2)

# Checking the model assumptions for the model2: 
par(mfrow=c(2,2))
plot(model2)

#we throw out
data_base2 = data_base[-c(3474,1701,1612),]
  
```


```{r cross validation}
set.seed(2)
# For the number generator
# Split data 50:50 validation and training
train<-sample(3612, 1806)

# Fit data with training set
lm.fit<-lm(log_los ~ is30dayreadmit + cindex + evisit + age  + insurance_type + bp_systolic + heart_rate + respiration_rate, data_base, subset=train)
summary(lm.fit)


#dataset without influential outliers
set.seed(2)
train<-sample(3609, 1805)
lm.fit2<-lm(log_los ~ is30dayreadmit + cindex + evisit + age  + insurance_type + bp_systolic + heart_rate + respiration_rate, data_base2, subset=train)
summary(lm.fit2)

#the result changes and adjusted r square increases, thus we drop those three influential observations in this process.
```










```{r not useful}
# just need to put these codes in the end of paper

# stepwise???
data_fit=na.omit(data_fit)
mult.fit <- lm(log_los ~ ., na.action=na.exclude, data=data_fit)
step(mult.fit, direction='backward')
```

```{r}
# MLR - big model
mult.fit_1 <- lm(log_los ~ factor(is30dayreadmit) + factor(cindex) + evisit + age + factor(gender) + factor(marital_status) + factor(insurance_type) + bp_systolic + o2_sat + heart_rate +  respiration_rate, data=data_fit)
summary (mult.fit_1)
anova(mult.fit_1)
```

```{r}
mult.fit_2 <- lm(log_los ~ factor(is30dayreadmit) + factor(cindex) + evisit + age + factor(marital_status) + factor(insurance_type) + bp_systolic + heart_rate +  respiration_rate,data=data_fit)
anova(mult.fit_2,mult.fit_1)
#choose mult.fit_2
```

####model 2: containing bmi at first(deleted outliers and recoded as underweight, normal and overweight)
```{r filter}
patientdata2=patientdata %>% 
  filter(bmi>15 & bmi<40)
patientdata2=patientdata2[-c(1253,2111,681),]
```

```{r recode bmi as categorical}
# bmi <18.5 underweight >25 overweight
patientdata2=patientdata2 %>% 
mutate(bmi=ifelse(bmi <18.5,1,ifelse(bmi <25,0,2)))%>%
  mutate(bmi=factor(bmi))
```

```{r backward elimination step1:full model}
mult.fit1 <- lm(log_los ~ is30dayreadmit+mews+cindex+evisit+icu_flag+age+gender+race+marital_status+insurance_type+bmi+bp_diastolic+temperature+heart_rate+respiration_rate, data=patientdata2)
summary(mult.fit1)
```

```{r step2:-race}
mult.fit2 <- lm(log_los ~ is30dayreadmit+mews+cindex+evisit+icu_flag+age+gender+marital_status+insurance_type+bmi+bp_diastolic+temperature+heart_rate+respiration_rate, data=patientdata2)
summary(mult.fit2)
```

```{r step3:-temperature}
mult.fit3 <- lm(log_los ~ is30dayreadmit+mews+cindex+evisit+icu_flag+age+gender+marital_status+insurance_type+bmi+bp_diastolic+heart_rate+respiration_rate, data=patientdata2)
summary(mult.fit3)
```

```{r  step4:-icu_flag}
mult.fit4 <- lm(log_los ~ is30dayreadmit+mews+cindex+evisit+age+gender+marital_status+insurance_type+bmi+bp_diastolic+heart_rate+respiration_rate, data=patientdata2)
summary(mult.fit4)
```

```{r  step5:-mews}
mult.fit5 <- lm(log_los ~ is30dayreadmit+cindex+evisit+age+gender+marital_status+insurance_type+bmi+bp_diastolic+heart_rate+respiration_rate, data=patientdata2)
summary(mult.fit5)
```

```{r  step6:-marital_Status}
mult.fit6 <- lm(log_los ~ is30dayreadmit+cindex+evisit+age+gender+insurance_type+bmi+bp_diastolic+heart_rate+respiration_rate, data=patientdata2)
summary(mult.fit6)
```

```{r anova}
anova(mult.fit6)
```

```{r  step7:-gender}
mult.fit7 <- lm(log_los ~ is30dayreadmit+cindex+evisit+age+insurance_type+bmi+bp_diastolic+heart_rate+respiration_rate, data=patientdata2)
summary(mult.fit7)
```

```{r  -cindex}
mult.fit8 <- lm(log_los ~ is30dayreadmit+evisit+age+insurance_type+bmi+bp_diastolic+heart_rate+respiration_rate, data=patientdata2)
summary(mult.fit8)
```

```{r compare nested models with/without cindex}
anova(mult.fit8, mult.fit7)#keep cindex fit7
```

```{r residual plots}
par(mfrow=c(2,2))
plot(mult.fit7)
```

```{r cross validation 9}
set.seed(2)                         
train<-sample(2712, 1357)

lm.fit<-lm(log_los ~ is30dayreadmit+cindex+evisit+age+insurance_type+bmi+bp_diastolic+heart_rate+respiration_rate, patientdata2, subset=train)
summary(lm.fit)
mean((log_los-predict(lm.fit, patientdata2))[-train]^2)
###bmi levels are insignificant in predicting, try delete them
```

```{r cross validation -bmi}
set.seed(2)                         
train<-sample(2712, 1357)

lm.fit<-lm(log_los ~ is30dayreadmit+cindex+evisit+age+insurance_type+bp_diastolic+heart_rate+respiration_rate, patientdata2, subset=train)
summary(lm.fit)
mean((log_los-predict(lm.fit, patientdata2))[-train]^2)
###here we gain a adjR^2 of 13.7%
```




